### PR TITLE
updated v2.2.0

### PR DESCRIPTION
**Pull request by seanyen**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by seanyen** [comment]
@conda-forge/urdfdom This is ready for review and merge. Thanks!

**Comment by wolfv** [comment]
cool stuff!

**Comment by traversaro** [comment]
Hi @seanyen , not that unfortunately the ros2 version used here does not contain all the features present in the "official"  ros/urdfdom version, see https://github.com/ros/urdfdom_headers/issues/59#issuecomment-587492078 .

**Comment by seanyen** [comment]
> Hi @seanyen , not that unfortunately the ros2 version used here does not contain all the features present in the "official" ros/urdfdom version, see [ros/urdfdom_headers#59 (comment)](https://github.com/ros/urdfdom_headers/issues/59#issuecomment-587492078) .

Thanks for letting me know! You are really ahead on this front. :)

**Comment by traversaro** [comment]
> 
> 
> > Hi @seanyen , not that unfortunately the ros2 version used here does not contain all the features present in the "official" ros/urdfdom version, see [ros/urdfdom_headers#59 (comment)](https://github.com/ros/urdfdom_headers/issues/59#issuecomment-587492078) .
> 
> Thanks for letting me know! You are really ahead on this front. :)

Just because I had to debug a really nasty bug related to this (https://github.com/robotology/gym-ignition/issues/118#issuecomment-575372388). : )

**Pull request merged**
